#####################################################
### Play 4: Install packages on our Cloud VMs
#
# In this play, you should be installing all the packages
# you need for this assignment including pre reqs for Docker.
# This will also include Python packages installed via pip
#####################################################
- name: "Play 4 - Install various packages on Cloud VMs"
  hosts: CloudVMs # specified in the Inventory file
  remote_user:
    "{{ cloud_user }}" # since this play operates on the cloud
    # VMs, the user on those VMs is the
    # cloud_user variable
  become: true # by setting this, we perform operations with sudo privilege
  gather_facts: no
  collections:
    - ansible-base

  tasks: # the task to be performed
    # @@ You have to write the following child playbooks @@
    - import_tasks: tasks/playbook_install_apt_packages.yaml
    - import_tasks: tasks/playbook_install_pip_packages.yaml
