#####################################################
### Play 7: Set firewalld rules
#####################################################

- name: "Play 7 - Handle Firewalld policies"
  hosts: CloudVMs # specified in the Inventory file
  remote_user:
    "{{ cloud_user }}" # since this play operates on the cloud
    # VMs, the user on those VMs is the
    # cloud_user variable
  become:
    true # we set it here instead of doing per task unless
    # there is a need to use non-sudo for any subtask
  gather_facts: false
  collections:
    - ansible-base
    - community.general

  tasks: # the task to be performed
    - import_tasks: tasks/playbook_set_firewalld_rules.yaml
